package tests.example.nointerface;

import com.netflix.hystrix.HystrixCommand;
import com.netflix.hystrix.HystrixCommandGroupKey;
import javax.annotation.Generated;

@Generated(
        value = "Generated by com.thatjoemoore.hystrix.annotations.processor.HysWriter2",
        date = "{{CURRENT DATE HERE}}"
)
public class ClassLevelSayHiCommand extends HystrixCommand<String> {
    /**
     * The object that actually implements the logic */
    private final ClassLevel ___delegate___;

    public ClassLevelSayHiCommand(final ClassLevel delegate) {
        super(HystrixCommandGroupKey.Factory.asKey("ten.ClassLevel"));
        this.___delegate___ = delegate;
    }

    @Override
    protected String run() throws Exception {
        return ___delegate___.sayHi();
    }
}
