package tests.example.nointerface;

import javax.annotation.Generated;

@Generated(
        value = "Generated by com.thatjoemoore.hystrix.annotations.processor.HysWriter2",
        date = "{{CURRENT DATE HERE}}"
)
public class ClassLevelHystrixWrapper {
    /**
     * The object that actually implements the logic */
    private final ClassLevel ___delegate___;

    public ClassLevelHystrixWrapper(final ClassLevel delegate) {
        this.___delegate___ = delegate;
    }

    public String sayHi() {
        return new ClassLevelSayHiCommand(this.___delegate___).execute();
    }
}
