package tests.example.nointerface;

import com.netflix.hystrix.HystrixCommand;
import com.netflix.hystrix.HystrixCommandGroupKey;
import javax.annotation.Generated;

@Generated(
        value = "Generated by com.thatjoemoore.hystrix.annotations.processor.HysWriter2",
        date = "{{CURRENT DATE HERE}}"
)
public class MethodLevelRiskyCallCommand extends HystrixCommand<String> {
    /**
     * The object that actually implements the logic */
    private final MethodLevel ___delegate___;

    private final int arg_arg;

    public MethodLevelRiskyCallCommand(final MethodLevel delegate, final int arg_arg) {
        super(HystrixCommandGroupKey.Factory.asKey("ten.MethodLevel"));
        this.___delegate___ = delegate;
        this.arg_arg = arg_arg;
    }

    @Override
    protected String run() throws Exception {
        return ___delegate___.riskyCall(this.arg_arg);
    }
}
