package tests.example.basic;

import javax.annotation.Generated;

@Generated(
        value = "Generated by com.thatjoemoore.hystrix.annotations.processor.HysWriter2",
        date = "{{CURRENT DATE HERE}}"
)
public class RemoteServiceHystrixFacade implements RemoteService {
    /**
     * The object that actually implements the logic */
    private final RemoteService ___delegate___;

    public RemoteServiceHystrixFacade(final RemoteService delegate) {
        this.___delegate___ = delegate;
    }

    @Override
    public String doSomething(final String arg_input) {
        return new RemoteServiceDoSomethingCommand(this.___delegate___, arg_input).execute();
    }

    @Override
    public int somethingElse(final int arg_one, final int arg_two) {
        return new RemoteServiceSomethingElseCommand(this.___delegate___, arg_one, arg_two).execute();
    }
}
