package tests.example.basic;

import com.netflix.hystrix.HystrixCommand;
import com.netflix.hystrix.HystrixCommandGroupKey;
import javax.annotation.Generated;

@Generated(
        value = "Generated by com.thatjoemoore.hystrix.annotations.processor.HysWriter2",
        date = "{{CURRENT DATE HERE}}"
)
public class RemoteServiceSomethingElseCommand extends HystrixCommand<Integer> {
    /**
     * The object that actually implements the logic */
    private final RemoteService ___delegate___;

    private final int arg_one;

    private final int arg_two;

    public RemoteServiceSomethingElseCommand(final RemoteService delegate, final int arg_one, final int arg_two) {
        super(HystrixCommandGroupKey.Factory.asKey("teb.RemoteService"));
        this.___delegate___ = delegate;
        this.arg_one = arg_one;
        this.arg_two = arg_two;
    }

    @Override
    protected Integer run() throws Exception {
        return ___delegate___.somethingElse(this.arg_one, this.arg_two);
    }
}
