package tests.example.basic.commands;

import com.netflix.hystrix.HystrixCommand;
import com.netflix.hystrix.HystrixCommandGroupKey;
import javax.annotation.Generated;
import tests.example.basic.ExampleService;

@Generated(
    value = "Generated by com.thatjoemoore.utils.hystrix.annotations.processor.HysWriter2",
    date = "{{CURRENT DATE HERE}}"
)
public class ExampleServiceDoSomethingCommand extends HystrixCommand<Integer> {
  /**
   * The object that actually implements the logic */
  private final ExampleService ___delegate___;

  private final String arg_input;

  public ExampleServiceDoSomethingCommand(final ExampleService delegate, final String arg_input) {
    super(HystrixCommandGroupKey.Factory.asKey("teb.ExampleService"));
    this.___delegate___ = delegate;
    this.arg_input = arg_input;
  }

  @Override
  protected Integer run() throws Exception {
    return ___delegate___.doSomething(this.arg_input);
  }
}