package tests.example.basic.commands;

import javax.annotation.Generated;
import tests.example.basic.ExampleService;

@Generated(
        value = "Generated by com.thatjoemoore.utils.hystrix.annotations.processor.HysWriter2",
        date = "{{CURRENT DATE HERE}}"
)
public class ExampleServiceHystrixWrapper implements ExampleService {
    /**
     * The object that actually implements the logic */
    private final ExampleService ___delegate___;

    ExampleServiceHystrixWrapper(final ExampleService delegate) {
        this.___delegate___ = delegate;
    }

    @Override
    public int doSomething(final String arg_input) {
        return new ExampleServiceDoSomethingCommand(this.___delegate___, arg_input).execute();
    }
}
